"""friday_night

Revision ID: 0e382048abd3
Revises: a6fa7846aea8
Create Date: 2024-12-21 00:32:50.340096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e382048abd3'
down_revision = 'a6fa7846aea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('appointment', sa.String(length=25), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('amount_paid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_bookings_product_id_products')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_bookings_service_id_services')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    # ### end Alembic commands ###
