"""Add new columns for images in Service and Product tables

Revision ID: c0f3ad2cfca5
Revises: 0e382048abd3
Create Date: 2025-01-09 09:30:05.429057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f3ad2cfca5'
down_revision = '0e382048abd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('before_service_image', sa.String(length=200), nullable=True))
    op.add_column('services', sa.Column('after_service_image', sa.String(length=200), nullable=True))
    op.drop_column('services', 'service_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('service_img', sa.VARCHAR(length=200), nullable=True))
    op.drop_column('services', 'after_service_image')
    op.drop_column('services', 'before_service_image')
    # ### end Alembic commands ###
